import { app, autoUpdater, BrowserWindow } from 'electron';
import { logError, logInfo, logWarn } from './logger';

/*
 * Auto-update module.
 *
 * Goal: ship a release on GitHub → users automatically receive it from
 * inside the app. No more "click the GitHub link to download".
 *
 * Engine: Electron's built-in Squirrel updater. It reads the
 * `RELEASES` + `.nupkg` assets uploaded by Electron Forge's
 * MakerSquirrel output through update.electronjs.org.
 *
 * State machine surfaced to the renderer:
 *   - 'unsupported': dev build / Linux / no signed installer. Banner stays hidden.
 *   - 'idle':        we've checked (or will), but no update is pending.
 *   - 'checking':    a check is in flight (rarely visible — usually <1s).
 *   - 'available':   reserved for explicit-download updater flows.
 *   - 'downloading': Squirrel found an update and is fetching it.
 *   - 'ready':       download complete, ready to install on quit/restart.
 *   - 'error':       transient failure; we'll retry on the next interval.
 *
 * The renderer shows a small notch in the sidebar driven by this
 * state. Errors stay silent in the UI (logged for debugging) — we
 * don't want auto-update flakiness to bother end-users.
 */

export type UpdateState =
  | 'unsupported'
  | 'idle'
  | 'checking'
  | 'available'
  | 'downloading'
  | 'ready'
  | 'error';

export interface UpdateStatusPayload {
  state: UpdateState;
  /** Version of the pending update (set in 'available' / 'downloading' / 'ready'). */
  version: string | null;
  /** 0..100, only meaningful in 'downloading'. */
  progress: number | null;
  /** Last error message (only set in 'error'). */
  error: string | null;
  /** ISO timestamp of the last successful check. */
  lastCheckedAt: string | null;
}

const REPO_OWNER = 'Aamirazmy92';
const REPO_NAME = 'Echo';
// Re-check the GitHub feed every hour. The first check fires on init
// so users running an older app for days still pick up new releases.
const PERIODIC_CHECK_MS = 60 * 60 * 1000;

let currentStatus: UpdateStatusPayload = {
  state: 'unsupported',
  version: null,
  progress: null,
  error: null,
  lastCheckedAt: null,
};

let initialised = false;

const listeners = new Set<(status: UpdateStatusPayload) => void>();

function setStatus(patch: Partial<UpdateStatusPayload>): void {
  currentStatus = { ...currentStatus, ...patch };
  for (const listener of listeners) {
    try {
      listener(currentStatus);
    } catch (err) {
      logWarn('updater', 'listener threw');
      void err;
    }
  }
}

/**
 * Subscribe to status changes. The current status is replayed
 * synchronously so late subscribers never miss a state.
 */
export function onUpdateStatus(callback: (status: UpdateStatusPayload) => void): () => void {
  listeners.add(callback);
  try {
    callback(currentStatus);
  } catch {
    /* ignore */
  }
  return () => listeners.delete(callback);
}

export function getUpdateStatus(): UpdateStatusPayload {
  return currentStatus;
}

/**
 * Initialise auto-updates. Idempotent — safe to call once at app
 * startup. In dev / unpackaged builds we mark state 'unsupported' and
 * return without touching `autoUpdater` (which would otherwise throw
 * because Squirrel update checks only work from an installed package).
 */
export function initAutoUpdater(): void {
  if (initialised) return;
  initialised = true;

  if (!app.isPackaged) {
    logInfo('updater', 'skipping auto-update (dev / unpackaged build)');
    setStatus({ state: 'unsupported' });
    return;
  }

  // Point Squirrel at our GitHub releases via update.electronjs.org.
  // The service resolves the latest release and serves the `RELEASES`
  // file + `.nupkg` generated by Electron Forge's MakerSquirrel.
  try {
    autoUpdater.setFeedURL({
      url: `https://update.electronjs.org/${REPO_OWNER}/${REPO_NAME}/${process.platform}-${process.arch}/${app.getVersion()}`,
    });
  } catch (err) {
    logError('updater', 'failed to configure update feed', err);
    setStatus({ state: 'unsupported' });
    return;
  }

  // Electron's built-in Squirrel updater downloads automatically once
  // an update is found, so the renderer moves straight from "checking"
  // to "downloading" to "restart to install".
  autoUpdater.on('checking-for-update', () => {
    // Don't blow away an already-known 'available' / 'ready' state if
    // the periodic re-check kicks in while a download is queued.
    if (currentStatus.state === 'idle' || currentStatus.state === 'error') {
      setStatus({ state: 'checking', error: null });
    }
  });

  autoUpdater.on('update-available', () => {
    setStatus({
      state: 'downloading',
      version: null,
      progress: null,
      error: null,
      lastCheckedAt: new Date().toISOString(),
    });
  });

  autoUpdater.on('update-not-available', () => {
    setStatus({
      state: 'idle',
      version: null,
      progress: null,
      error: null,
      lastCheckedAt: new Date().toISOString(),
    });
  });

  autoUpdater.on('update-downloaded', (_event, _releaseNotes, releaseName) => {
    logInfo('updater', `update downloaded: ${releaseName ?? 'unknown version'}`);
    setStatus({
      state: 'ready',
      version: releaseName ?? currentStatus.version,
      progress: 100,
      error: null,
    });
  });

  autoUpdater.on('error', (err: Error) => {
    logWarn('updater', `autoUpdater error: ${err?.message ?? err}`);
    setStatus({ state: 'error', error: err?.message ?? String(err) });
  });

  setStatus({ state: 'idle' });

  // Kick an initial check, then poll on an interval. Both are wrapped
  // so a transient network blip just logs without crashing startup.
  void runCheck('initial');
  setInterval(() => {
    // Skip periodic checks once a download is already queued — no
    // point re-asking the feed when we know there's something newer.
    if (currentStatus.state === 'available' ||
        currentStatus.state === 'downloading' ||
        currentStatus.state === 'ready') {
      return;
    }
    void runCheck('periodic');
  }, PERIODIC_CHECK_MS);
}

async function runCheck(label: string): Promise<void> {
  try {
    autoUpdater.checkForUpdates();
  } catch (err) {
    logWarn('updater', `${label} check failed`, err);
  }
}

/**
 * Force an update check on demand. No-op outside packaged builds.
 */
export function checkForUpdatesNow(): void {
  if (!app.isPackaged) return;
  void runCheck('manual');
}

/**
 * Squirrel downloads automatically after `checkForUpdates()`. This is
 * kept for the renderer IPC shape but is intentionally a soft no-op.
 */
export function downloadUpdateNow(): void {
  if (!app.isPackaged) return;
  logWarn('updater', `downloadUpdateNow called in state '${currentStatus.state}', ignoring`);
}

/**
 * Quit the app and install the downloaded update. Caller must verify
 * `state === 'ready'` first.
 */
export function installAndRestart(): void {
  if (currentStatus.state !== 'ready') {
    logWarn('updater', `installAndRestart called in state '${currentStatus.state}', ignoring`);
    return;
  }
  logInfo('updater', 'quitAndInstall — restarting into new version');
  autoUpdater.quitAndInstall();
}

/**
 * Helper used by `index.ts` to forward status changes to a window
 * over the `update-status` channel.
 */
export function broadcastUpdateStatusTo(window: BrowserWindow): () => void {
  return onUpdateStatus((status) => {
    if (window.isDestroyed()) return;
    window.webContents.send('update-status', status);
  });
}
